### ISSUE TITLE
Pet stops following normally after dismounting.

### ISSUE THREAD

**Issue by kabluinc** [Sandertv/BlockPets#2]
Many thanks for making this plugin! One issue iv come across while testing it is that once you dismount from the pet, it will continue trying to run forward and come back to u again. It will keep doing this until you relog, after which it starts following you as normal again.

**Comment by Sandertv** [comment]
Hmmm, I haven't had this issue yet. I'll look into it :)

**Comment by Sandertv** [comment]
Could I ask if the pets do follow you through worlds btw? I haven't tested it yet 😛

**Comment by kabluinc** [comment]
They didn't follow after switching worlds when I tested it. The pet disappeared and even after going back to the original world it was not there.

**Comment by Sandertv** [comment]
Hmmm... I'll have to look into that too.

**Comment by Sandertv** [comment]
For the not able to switch worlds, do you get any errors in console? I've had experience with PurePerms giving an error if the entity switching worlds is not a player.

**Comment by kabluinc** [comment]
Yep pureperms shows those errors

**Comment by Sandertv** [comment]
I'm not entirely sure if it IS the problem, but you can fix it by using this version: https://github.com/poggit-orphanage/PurePerms
The original plugin is lacking a check if the entity changing worlds is a player, which this version does do.

**Comment by kabluinc** [comment]
When pets are ridden, they are very Maggy and move in chunks rather than moving slowly. Its a bit like those rideable minecarts a spoon of pocketmine once had that acted like cars. At first they weren't so smooth but one day all of a sudden they moved perfectly.

Would it even be possible to make it so you can control their movement yourself using the arrow keys like MCPC. This was implemented on minecarts once in a spoon.

Otherwise excellent plugin. Thanks allot for making it.

**Comment by Sandertv** [comment]
They move in chunks? 

And yeah, I'm looking into using the arrows at the moment.

**Comment by Sandertv** [comment]
You might want to try and test the latest version. I've implemented experimental arrow driven riding of the pets, but it might not work.

**Comment by kabluinc** [comment]
idk if I'm doing something wrong but when I tap a pet with a saddle, they keep getting damage and doesn't ride the player anymore. Weird

**Comment by Sandertv** [comment]
Hmmm, lemme look into it.

**Comment by Sandertv** [comment]
Is there any error again?

**Comment by kabluinc** [comment]
Nope. no errors.

**Comment by Sandertv** [comment]
My apologies, it's fixed in the latest commit.

**Comment by kabluinc** [comment]
Np. Thanks

**Comment by Sandertv** [comment]
Alright, I've tested the arrow driven movement, and it sort of works. It's DEFINITELY not flawless yet, but it's a start. My local version allows you to somewhat go where you want to go. The original issue is quite annoying to deal with though. MCPE handles the unmounting of pets using the jump or sneak button, and I can't manage it. Maybe I can find a workaround for it.

**Comment by Sandertv** [comment]
I've added a workaround for this issue in latest commits. This workaround at the moment causes pets to spin around in circles when mounted after a second or 3 and make them unable to be controlled again. I'm going to try and improve this.

**Comment by Sandertv** [comment]
Fixed it in a clean way and it works fawlessly again! Closing it now. :)

**Comment by Sandertv** [comment]
Cross world pets work perfectly now too! :)

**Comment by kabluinc** [comment]
Amazing!! Thanks for your effort in making such an amazing plugin ;)

**Comment by Sandertv** [comment]
No problem, I like doing it. :)
The plugin's still got a long way to go, but the base is there.
