### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by LordJoshie** [Sandertv/BlockPets#3]
Dont know if this is a private project or not, but I went to try it and I wasn't able to run any commands... 

not even /help or anything.

**Comment by Sandertv** [comment]
This only works correctly with PocketMine. Tesseract does not have the same implementation as PocketMine, and thus does not work.

**Comment by Sandertv** [comment]
I can't fix this issue for you, sorry.

**Comment by LordJoshie** [comment]
Okay, no worries. 

I have a PMMP server also. 

I have like 5 diff test platforms, but Tess works the best for me.

**Comment by LordJoshie** [comment]
Doesn't work with PMMP either. lol

**Comment by Sandertv** [comment]
It works perfectly fine for me on my test server.

**Comment by LordJoshie** [comment]
Well, i got the latest pmmp network branch with sounds and your plugin, and
it threw errors saying something in walking pet needed to be public... I
could make it work, but it's your plugin....

**Comment by Sandertv** [comment]
Oh yeah, that's right, I got that fixed on my public version already. It got messed up because the jump() function got added in PMMP. I'll push the commit soon.
