### ISSUE TITLE
Pet doesnt re-appear after relog

### ISSUE THREAD

**Issue by kabluinc** [Sandertv/BlockPets#9]
Hi.

After doing some testing I found that after u spawn a pet, it does follow you when u switch worlds as normal. However when you relog, it does not reappear. My server uses 'alwaysspawn' plugin so you always respawn to a the lobby world when relogging. However when you go back to the world you last had your pet at, forexample a creative world, it reappears and starts following again.

My question was that is it possible for any pets you have to appear and start following you where you spawn at?

**Comment by Sandertv** [comment]
Hi there! My bad, I accidentally removed a part of the code I shouldn't have removed. I'll fix it within an hour! :)

**Comment by kabluinc** [comment]
Thanks allot :)
